"""init

Revision ID: 3e3be155ebd6
Revises: 89fccc41e2b8
Create Date: 2023-12-20 18:30:28.226669

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e3be155ebd6'
down_revision: Union[str, None] = '89fccc41e2b8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_time')
    # ### end Alembic commands ###
