"""init

Revision ID: b3fa8a34077f
Revises: 3e3be155ebd6
Create Date: 2023-12-20 20:01:54.220316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'b3fa8a34077f'
down_revision: Union[str, None] = '3e3be155ebd6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'join_time')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('join_time', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
